export const DEFAULT_COLORS_PALETTE = [
  { title: "black", color: "#000000" },
  { title: "dark gray 4", color: "#434343" },
  { title: "dark gray 3", color: "#666666" },
  { title: "dark gray 2", color: "#999999" },
  { title: "dark gray 1", color: "#b7b7b7" },
  { title: "gray", color: "#cccccc" },
  { title: "light gray 1", color: "#d9d9d9" },
  { title: "light gray 2", color: "#efefef" },
  { title: "light gray 3", color: "#f3f3f3" },
  { title: "white", color: "#ffffff" },
  { title: "red berry", color: "#980000" },
  { title: "red", color: "#ff0000" },
  { title: "orange", color: "#ff9900" },
  { title: "yellow", color: "#ffff00" },
  { title: "green", color: "#00ff00" },
  { title: "cyan", color: "#00ffff" },
  { title: "cornflower blue", color: "#4a86e8" },
  { title: "blue", color: "#0000ff" },
  { title: "purple", color: "#9900ff" },
  { title: "magenta", color: "#ff00ff" },
  { title: "light red berry 3", color: "#e6b8af" },
  { title: "light red 3", color: "#f4cccc" },
  { title: "light orange 3", color: "#fce5b5" },
  { title: "light yellow 3", color: "#fff2cc" },
  { title: "light green 3", color: "#d9ead3" },
  { title: "light cyan 3", color: "#d0e0e3" },
  { title: "light cornflower blue 3", color: "#c9daf8" },
  { title: "light blue 3", color: "#cfe2f3" },
  { title: "light purple 3", color: "#d9d2e9" },
  { title: "light magenta 3", color: "#ead1dc" },
  { title: "light red berry 2", color: "#dd7e6b" },
  { title: "light red 2", color: "#ea9999" },
  { title: "light orange 2", color: "#f9cb9c" },
  { title: "light yellow 2", color: "#ffe599" },
  { title: "light green 2", color: "#b6d7a8" },
  { title: "light cyan 2", color: "#a2c4c9" },
  { title: "light cornflower blue 2", color: "#a4c2f4" },
  { title: "light blue 2", color: "#9fc5e8" },
  { title: "light purple 2", color: "#b4a7d6" },
  { title: "light magenta 2", color: "#d5a6bd" },
  { title: "light red berry 1", color: "#cc4125" },
  { title: "light red 1", color: "#e06464" },
  { title: "light orange 1", color: "#f6b26b" },
  { title: "light yellow 1", color: "#ffda66" },
  { title: "light green 1", color: "#93c87d" },
  { title: "light cyan 1", color: "#76a5af" },
  { title: "light cornflower blue 1", color: "#6d9eeb" },
  { title: "light blue 1", color: "#6fa8dc" },
  { title: "light purple 1", color: "#8e7cc3" },
  { title: "light magenta 1", color: "#c276a0" },
  { title: "dark red berry 1", color: "#a61c00" },
  { title: "dark red 1", color: "#cc0000" },
  { title: "dark orange 1", color: "#e69138" },
  { title: "dark yellow 1", color: "#f1c236" },
  { title: "dark green 1", color: "#6aa84f" },
  { title: "dark cyan 1", color: "#458b8e" },
  { title: "dark cornflower blue 1", color: "#3c78d8" },
  { title: "dark blue 1", color: "#3d85c6" },
  { title: "dark purple 1", color: "#674ea7" },
  { title: "dark magenta 1", color: "#a64d79" },
  { title: "dark red berry 2", color: "#851c0c" },
  { title: "dark red 2", color: "#990000" },
  { title: "dark orange 2", color: "#b46306" },
  { title: "dark yellow 2", color: "#bf9000" },
  { title: "dark green 2", color: "#387629" },
  { title: "dark cyan 2", color: "#134f5c" },
  { title: "dark cornflower blue 2", color: "#1155cc" },
  { title: "dark blue 2", color: "#0b5394" },
  { title: "dark purple 2", color: "#351c75" },
  { title: "dark magenta 2", color: "#742b47" },
  { title: "dark red berry 3", color: "#5b0f00" },
  { title: "dark red 3", color: "#660000" },
  { title: "dark orange 3", color: "#783f04" },
  { title: "dark yellow 3", color: "#7f6000" },
  { title: "dark green 3", color: "#273e13" },
  { title: "dark cyan 3", color: "#0c343d" },
  { title: "dark cornflower blue 3", color: "#1c4587" },
  { title: "dark blue 3", color: "#073763" },
  { title: "dark purple 3", color: "#20124d" },
  { title: "dark magenta 3", color: "#4c112f" },
]
